#!/bin/sh 

. $(dirname $0)/common/_log
. $(dirname $0)/common/_notify
echo $$

#Load config
DDNS_CONFIG_FILE=${1-$HOME/.ddns_config/brouter.shikun.win}

accessKeyID=`grep "accessKeyId" $DDNS_CONFIG_FILE|sed 's/.*=\ //g'`
accessKeySecret=`grep "accessKeySecret" $DDNS_CONFIG_FILE|sed 's/.*=\ //g'`
recordID=`grep "recordID" $DDNS_CONFIG_FILE|sed 's/.*=\ //g'`
RR=`grep "RR" $DDNS_CONFIG_FILE|sed 's/.*=\ //g'`

#Get ips
IP=`ip addr show ppp0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1`
CURRENT_RESOLVED_IP=`nslookup $RR.shikun.win dns9.hichina.com|grep -A1 Name|grep Address|awk -F": " '{print $2}'`
echo IP:$IP
echo CURRENT_RESOLVED_IP:$CURRENT_RESOLVED_IP

if [ X"$IP" == X"$CURRENT_RESOLVED_IP" ]
then
	echo "$RR.shikun.win is up-to-date, not updated it."
        /sbin/ddns_custom_updated 0
	exit 
fi

[ -z $CURRENT_RESOLVED_IP ] && log "dns resolved failed"  && exit 1

log "$RR.shikun.win is updated, result: $(/mnt/sda1/MGMT/ddns/aliyun_ddns.py $IP $accessKeyID $accessKeySecret $recordID $RR)"
send_notify "DDNS Updated" "$RR.shikun.win -> ${CURRENT_RESOLVED_IP}"

/sbin/ddns_custom_updated 
